# Generated by Django 4.1.7 on 2023-06-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomID', models.AutoField(primary_key=True, serialize=False)),
                ('roomType', models.CharField(max_length=100)),
                ('roomName', models.CharField(max_length=100)),
                ('buildingNumber', models.IntegerField()),
                ('blockNumber', models.IntegerField()),
                ('floorNumber', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
